image: node:latest
before_script:
    - echo "$env_config" > ".env"
    - cat .env
variables:
  HUSKY: 0
cache:
  paths:
    - node_modules/
    - .yarn
test_api:
  script:
    - yarn install
    - yarn test
