image: buildkite/puppeteer:latest
before_script:
    - echo "$env_config" > ".env"
    - echo "$github_cookie" > "github.cookie.json"
    - export "HUSKY=0"
    - apt-get update && apt-get install -y procps
cache:
  paths:
    - node_modules/
    - .yarn
test_api:
  only:
    - pushes
  script:
    - yarn install
    - yarn test --runInBand
