openapi: '3.0.0'
tags:
- name: user
  description: Operations about user
servers:
- url: https://api.realdev.in/
- url: http://localhost:5000/api
schemes:
- https
- http
info:
  $ref: ./api-docs/info.yaml
paths:
  /auth/login:
    $ref: ./api-docs/paths/index.yaml#/login
  /auth/register:
    $ref: ./api-docs/paths/index.yaml#/register
  /auth/forgot_password:
    $ref: ./api-docs/paths/index.yaml#/forgot_password
  /auth/reset_password:
    $ref: ./api-docs/paths/index.yaml#/reset_password
  /auth/oauth/redirect/github:
    $ref: ./api-docs/paths/index.yaml#/redirect_github
  /auth/oauth/signin/github:
    $ref: ./api-docs/paths/index.yaml#/signin_github
  /auth/oauth/redirect/google:
    $ref: ./api-docs/paths/index.yaml#/redirect_google
  /auth/oauth/signin/google:
    $ref: ./api-docs/paths/index.yaml#/signin_google
components:
  responses:
      $ref: "./api-docs/responses.yaml"
  schemas:
    LoginForm:
      $ref: "./api-docs/schema/index.yaml#/LoginForm"
    RegisterForm:
      $ref: "./api-docs/schema/index.yaml#/RegisterForm"
    Oauth:
      $ref: "./api-docs/schema/index.yaml#/Oauth"
    ForgotPasswordForm:
      $ref: "./api-docs/schema/index.yaml#/ForgotPasswordForm"
    ResetPasswordForm:
      $ref: "./api-docs/schema/index.yaml#/ResetPasswordForm"
