openapi: '3.0.0'
servers:
- url: http://localhost:5000/api
tags:
- name: user
  description: Operations about user
schemes:
- https
- http
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
