openapi: '3.0.0'
tags:
- name: user
  description: Operations about user
servers:
- url: https://api.realdev.in/
- url: http://localhost:5000/
schemes:
- https
- http
info:
  $ref: ./api-docs/info.yaml
paths:
  /login:
    $ref: ./api-docs/paths/index.yaml#/login
  /register:
    $ref: ./api-docs/paths/index.yaml#/register
components:
  responses:
      $ref: "./api-docs/responses.yaml"
  schemas:
    LoginForm:
      $ref: "./api-docs/schema/index.yaml#/LoginForm"
    RegisterForm:
      $ref: "./api-docs/schema/index.yaml#/RegisterForm"
