import express from 'express';
import * as authController from '../controllers/userController/authController.js';
import * as passwordController from '../controllers/userController/passwordController.js';
import * as passwordValidator from '../validators/passwordValidator';
import loginValidator from '../validators/loginValidator';
import registerValidator from '../validators/registerValidator';
import { celebrate } from 'celebrate';
const userRouter = express.Router();
userRouter.post('/register', celebrate({ body: registerValidator, }), authController.register);
userRouter.post('/login', celebrate({ body: loginValidator, }), authController.login);
userRouter.get('/oauth/redirect/github', authController.githubAuthRedirect);
userRouter.post('/oauth/signin/github', authController.githubAuth);
userRouter.get('/oauth/redirect/google',  authController.googleRedirect);
userRouter.post('/oauth/signin/google',  authController.googleAuth);
userRouter.post('/forgot_password', celebrate({ body: passwordValidator.ForgotPasswordvalidateScheama, }), passwordController.forgotPassword);
userRouter.post('/reset_password', celebrate({ body: passwordValidator.ResetPasswordvalidateScheama, }), passwordController.resetPassword);
export default userRouter;
